# Molecular Biology (Promoter Gene Sequences) - EDA

## Objective: Understand the dataset

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/promoters.data")
df.head()

   +        S10 \t\ttactagcaatacgcttgcgttcggtggttaagtatgtataatgcgcgggcttgtcgt
0  +       AMPC  \t\ttgctatcctgacagttgtcacgctgattggtgtcgttacaat...
1  +       AROH  \t\tgtactagagaactagtgcattagcttatttttttgttatcat...
2  +      DEOP2  \taattgtgatgtgtatcgaagtgtgttgcggagtagatgttagaa...
3  +  LEU1_TRNA  \ttcgataattaactattgacgaaaagctgaaaaccactagaatgc...
4  +     MALEFG  \taggggcaaggaggatggaaagaggttgccgtataaagaaactag...

In [10]:
df.shape

(106, 3)

The data comes with no header, but from the uci page, we know 
1. +/- refers to whether the dna sequenc is a promoter(+) or not (-)
2. it is an identifer name
3. sequence of dna, hence containing agct -> length - 57

In [3]:
column_names = ["class", "identifier", "sequence"]
df = pd.read_csv("../data/raw/promoters.data", header=None, names=column_names)
df.head()

  class identifier                                           sequence
0     +        S10  \t\ttactagcaatacgcttgcgttcggtggttaagtatgtataat...
1     +       AMPC  \t\ttgctatcctgacagttgtcacgctgattggtgtcgttacaat...
2     +       AROH  \t\tgtactagagaactagtgcattagcttatttttttgttatcat...
3     +      DEOP2  \taattgtgatgtgtatcgaagtgtgttgcggagtagatgttagaa...
4     +  LEU1_TRNA  \ttcgataattaactattgacgaaaagctgaaaaccactagaatgc...

In [9]:
df.shape

(106, 3)

There is an issue with the way dna sequence has been formatted with tabs and newlines so we strip it

In [4]:
df['sequence'] = df['sequence'].str.strip()
df.head()

  class identifier                                           sequence
0     +        S10  tactagcaatacgcttgcgttcggtggttaagtatgtataatgcgc...
1     +       AMPC  tgctatcctgacagttgtcacgctgattggtgtcgttacaatctaa...
2     +       AROH  gtactagagaactagtgcattagcttatttttttgttatcatgcta...
3     +      DEOP2  aattgtgatgtgtatcgaagtgtgttgcggagtagatgttagaata...
4     +  LEU1_TRNA  tcgataattaactattgacgaaaagctgaaaaccactagaatgcgc...

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 106 entries, 0 to 105
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   class       106 non-null    str
 1   identifier  106 non-null    str
 2   sequence    106 non-null    str
dtypes: str(3)
memory usage: 2.6 KB

In [15]:
df.isnull().sum()

class         0
identifier    0
sequence      0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [7]:
df['sequence'].str.len().value_counts()

sequence
57    106
Name: count, dtype: int64

All the rows have the same 57 length as mentioned in the dataset.

Why does it contain 57 positions?  
  
Promoters are sequence of dna/rna which tells the rna polymerase to start transcribing.  
rna polymerase binds to the promoter, and then starts transcribing.  
  
In ecoli, promoter length is around ~35. In our dataset, they have included +7(p7) sequences that will be transcribed.  
By convention, 
    position + 1 is where transcription starts (Transcription Start Site - TSS)
    positions before it are negative and
    positions after it are positive
There is no position 0

-50, ...., -1, p+1, ..., p+7

In [11]:
df['class'].value_counts()

class
+    53
-    53
Name: count, dtype: int64

In [20]:
df['class'].value_counts(normalize=True)

class
+    0.5
-    0.5
Name: proportion, dtype: float64

This is a fairly balanced dataset since it has equal number of promoters and non promoters.  
This is important because class imbalance can affect model training and evaluation

In [19]:
set("".join(df["sequence"]))

{'a', 'c', 'g', 't'}

Data set contains only A, C, G, T nucleotides